"""Make nick not nullable

Revision ID: 089eb92b2b90
Revises: cbe4fd8034d0
Create Date: 2021-09-17 00:21:17.953603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '089eb92b2b90'
down_revision = 'cbe4fd8034d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('club_members', 'nick',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('club_members', 'nick',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
