"""Make Club -> User two way relationship

Revision ID: 2ebb38f8939c
Revises: e0600a6fd5e4
Create Date: 2022-01-14 22:56:17.525519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ebb38f8939c'
down_revision = 'e0600a6fd5e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplace_items',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('cost', sa.BIGINT(), nullable=True),
    sa.Column('object_id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('object_type', sa.Enum('MEMBER', name='objecttype'), nullable=False),
    sa.Column('seller_id', sa.BIGINT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('club_members', sa.Column('value', sa.BIGINT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('club_members', 'value')
    op.drop_table('marketplace_items')
    # ### end Alembic commands ###
