"""Make discord_id pk

Revision ID: 6533928c419e
Revises: 8dcb88a89ca4
Create Date: 2021-09-17 00:02:10.813525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6533928c419e'
down_revision = '8dcb88a89ca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'discord_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'discord_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
