"""make discord_id not unique

Revision ID: 786bf0479d37
Revises: 9a8b912676b0
Create Date: 2022-01-31 23:58:05.092666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '786bf0479d37'
down_revision = '9a8b912676b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_discord_id_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_discord_id_key', 'users', ['discord_id'])
    # ### end Alembic commands ###
