"""Intial migration

Revision ID: 8dcb88a89ca4
Revises: 
Create Date: 2021-09-16 23:51:05.617116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dcb88a89ca4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('money', sa.BIGINT(), nullable=True),
    sa.Column('guild_id', sa.BIGINT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('discord_id', sa.BIGINT(), nullable=True),
    sa.Column('money', sa.BIGINT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('guild_id', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('club_members',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('nick', sa.String(), nullable=False),
    sa.Column('club_id', sa.BIGINT(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('club_members')
    op.drop_table('users')
    op.drop_table('clubs')
    # ### end Alembic commands ###
