"""Add cascading option to fix the server deletion

Revision ID: 9a8b912676b0
Revises: 6399928d5df7
Create Date: 2022-01-29 23:13:22.632885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a8b912676b0'
down_revision = '6399928d5df7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('club_members_club_id_fkey', 'club_members', type_='foreignkey')
    op.drop_constraint('club_members_id_fkey', 'club_members', type_='foreignkey')
    op.create_foreign_key(None, 'club_members', 'users', ['id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'club_members', 'clubs', ['club_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'club_members', type_='foreignkey')
    op.drop_constraint(None, 'club_members', type_='foreignkey')
    op.create_foreign_key('club_members_id_fkey', 'club_members', 'users', ['id'], ['id'])
    op.create_foreign_key('club_members_club_id_fkey', 'club_members', 'clubs', ['club_id'], ['id'])
    # ### end Alembic commands ###
