"""Implement Transactions and add more features!

Revision ID: baee1b1c27f8
Revises: 2ebb38f8939c
Create Date: 2022-01-15 00:35:05.032946

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'baee1b1c27f8'
down_revision = '2ebb38f8939c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('cost', sa.BIGINT(), nullable=True),
    sa.Column('object_id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('object_type', sa.Enum('MEMBER', name='objecttype'), nullable=False),
    sa.Column('seller_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('item_id', sa.BIGINT(), nullable=False),
    sa.Column('seller_id', sa.BIGINT(), nullable=False),
    sa.Column('buyer_id', sa.BIGINT(), nullable=False),
    sa.Column('cost', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('marketplace_items')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplace_items',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('cost', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('object_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('object_type', postgresql.ENUM('MEMBER', name='objecttype'), autoincrement=False, nullable=False),
    sa.Column('seller_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='marketplace_items_pkey')
    )
    op.drop_table('transactions')
    op.drop_table('items')
    # ### end Alembic commands ###
